server:
  port: 8001
  servlet:
    context-path: /parking

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parking
    username: postgres
    password: fanti
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

rabbitmq:
  dynamic: false

parking:
  queue: parking

jwt:
  secret: fanti
