server:
  port: 8001
  servlet:
    context-path: /talentoUCO

spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/talentouco?useSSL=false
    username: root
    #password: 12345678
    password:
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

rabbitmq:
  dynamic: false

parking:
  queue: parking

jwt:
  secret: fanti
